image: steveblackburn/comp1110-2020-s2-gitlab-ci:0.1.1

stages:
  - build
  - test

before_script:
  - export CP=src:/exam/comp1110-exam-2020s2.jar:/exam/hamcrest-core-1.3.jar:/exam/junit-4.12.jar

build:
  tags:
    - comp1110
  stage: build
  script:
    - javac -encoding utf-8 $JAVAFX_OPTIONS -cp $CP src/comp1110/exam/*.java
  artifacts:
    paths:
      - src/comp1110/exam/*.class

P1:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.P1HelloWorldTest
  allow_failure: true

P2:
  tags:
    - comp1110
  stage: test
  script:
    - python3 /checkmc.py p-2.csv 4 abcde
  allow_failure: true

Q1.1Ceil:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1CeilTest
  allow_failure: true

Q1.1Closest:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1ClosestTest
  allow_failure: true

Q1.1Floor:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1FloorTest
  allow_failure: true

Q1.1Furthest:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1FurthestTest
  allow_failure: true

Q1.1Remainder:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1RemainderTest
  allow_failure: true

Q1.2Magic:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1MagicTest
  allow_failure: true

Q1.2Ox:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1OxTest
  allow_failure: true

Q1.2TwoThree:
    tags:
      - comp1110
    stage: test
    script:
      - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1TwoThreeTest
    allow_failure: true

Q1.2VowCon:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1VowConTest
  allow_failure: true

Q1.3Number:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1NumberTest
  allow_failure: true

Q1.3Word:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1WordTest
  allow_failure: true

Q1.3Bishop:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q1BishopTest
  allow_failure: true

Q2Caps:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q2CapsTest
  allow_failure: true

Q2Checksum:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q2ChecksumTest
  allow_failure: true

Q2Redact:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q2RedactTest
  allow_failure: true

Q3.1Hollywood:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q3HollywoodTest
  allow_failure: true

Q3.2Hollywood:
  tags:
    - comp1110
  stage: test
  script:
    - good=1; bad=0;
    - java -cp /exam/G:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoStarsTest || good=0
    - java -cp /exam/B0:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoStarsTest || b0=$?
    - if [ $b0 -eq 1 ]; then bad=$((bad+1)); fi;
    - java -cp /exam/B1:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoStarsTest || b1=$?
    - if [ $b1 -eq 1 ]; then bad=$((bad+1)); fi;
    - java -cp /exam/B2:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoStarsTest || b2=$?
    - if [ $b2 -eq 1 ]; then bad=$((bad+1)); fi;
    - java -cp /exam/B3:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoStarsTest || b3=$?
    - if [ $b3 -eq 1 ]; then bad=$((bad+1)); fi;
    - if [ $good -eq 0 ]; then echo; echo "Unit test rejected good program."; echo "0/5 marks"; false; fi
    - if [ $bad -ne 4 ]; then m=$(($bad+1)); echo; echo "Unit test passed good program but only rejected $bad/4 bad programs."; echo "$m/5 marks"; false; fi
    - if [ $bad -eq 4 ]; then echo; echo "Unit test passed good program and rejected 4 bad programs."; echo "5/5 marks"; fi
  allow_failure: true

Q3.1Library:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q3LibraryTest
  allow_failure: true

Q3.2Library:
  tags:
    - comp1110
  stage: test
  script:
    - good=1; bad=0;
    - java -cp /exam/G:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoauthorsTest || good=0
    - java -cp /exam/B0:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoauthorsTest || b0=$?
    - if [ $b0 -eq 1 ]; then bad=$((bad+1)); fi;
    - java -cp /exam/B1:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoauthorsTest || b1=$?
    - if [ $b1 -eq 1 ]; then bad=$((bad+1)); fi;
    - java -cp /exam/B2:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoauthorsTest || b2=$?
    - if [ $b2 -eq 1 ]; then bad=$((bad+1)); fi;
    - java -cp /exam/B3:$CP org.junit.runner.JUnitCore comp1110.exam.Q3GetMaxCoauthorsTest || b3=$?
    - if [ $b3 -eq 1 ]; then bad=$((bad+1)); fi;
    - if [ $good -eq 0 ]; then echo; echo "Unit test rejected good program."; echo "0/5 marks"; false; fi
    - if [ $bad -ne 4 ]; then m=$(($bad+1)); echo; echo "Unit test passed good program but only rejected $bad/4 bad programs."; echo "$m/5 marks"; false; fi
    - if [ $bad -eq 4 ]; then echo; echo "Unit test passed good program and rejected 4 bad programs."; echo "5/5 marks"; fi
  allow_failure: true

Q4FerrisWheel:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q4FerrisWheelTest
  allow_failure: true

Q4SushiTrain:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q4SushiTrainTest
  allow_failure: true

Q5Address:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q5AddressTest
  allow_failure: true

Q5Car:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q5CarTest
  allow_failure: true

Q5Actor:
  tags:
    - comp1110
  stage: test
  script:
    - java -cp $CP org.junit.runner.JUnitCore comp1110.exam.Q5ActorTest
  allow_failure: true

Q6:
  tags:
    - comp1110
  stage: test
  script:
    - python3 /checkmc.py q-6.csv 4 abcde
  allow_failure: true