https://tutorcs.com
WeChat: cstutorcs
QQ: 749389476
Email: tutorcs@163.com
package comp1110.exam;

import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.Timeout;
import org.junit.runners.MethodSorters;

import java.util.*;
import java.util.function.Consumer;
import java.util.function.Function;

import static junit.framework.TestCase.assertFalse;
import static org.junit.Assert.assertTrue;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Q5ActorTest {
    @Rule
    public Timeout globalTimeout = Timeout.millis(2000);

    public static final int HASH_ITERATIONS = 100;

    static Q5Actor[] actors = new Q5Actor[200 * HASH_ITERATIONS];

    @Test
    public void testHashCodeDeterministic() {
        checkNotObjectHashCode();
        for (Q5Actor actor : actors) {
            int hash = actor.hashCode();
            for (int i = 0; i < 10; i++) {
                int hash2 = actor.hashCode();
                assertTrue("actor " + actor + "  returned different values for hashCode(): " + hash + ", " + hash2, hash == hash2);
            }
        }
    }

    @Test
    public void testAllFields() {
        checkNotObjectHashCode();
        Q5Actor actor1 = new Q5Actor("Michelle", "Williams", "19800909");
        Q5Actor actor2 = new Q5Actor("Michelle", "Williams", "19790723");
        testDifferent(actor1, actor2);
        testDifferent(actor1, actor2);
        actor2 = new Q5Actor("Michelle", "Pfeiffer", "19800909");
        testDifferent(actor1, actor2);
        testDifferent(actor1, actor2);
        actor2 = new Q5Actor("Michelle", "Rodriguez", "19800909");
        testDifferent(actor1, actor2);
        testDifferent(actor1, actor2);
        actor2 = new Q5Actor("Robin", "Williams", "19800909");
        testDifferent(actor1, actor2);
        testDifferent(actor1, actor2);
        actor2 = new Q5Actor("Cara", "Williams", "19800909");
        testDifferent(actor1, actor2);
        testDifferent(actor1, actor2);
    }

    @Test
    public void testEquals() {
        Q5Actor actor1 = new Q5Actor("Michelle", "Williams", "19800909");
        assertTrue("actor1.equals(actor1) returned false", actor1.equals(actor1));
        Q5Actor actor2 = new Q5Actor("Michelle", "Williams", "19790723");
        assertFalse("actors " + actor1 + " and " + actor2 + " are not equal, but actor1.equals(actor2) returned true", actor1.equals(actor2));
        actor2.given = "Robin";
        actor2.dob = "19800909";
        assertFalse("actors " + actor1 + " and " + actor2 + " are not equal, but actor1.equals(actor2) returned true", actor1.equals(actor2));
        actor2.given = "Michelle";
        actor2.family = "Bridges";
        assertFalse("actors " + actor1 + " and " + actor2 + " are not equal, but actor1.equals(actor2) returned true", actor1.equals(actor2));
        actor2.family = null;
        assertFalse("actors " + actor1 + " and " + actor2 + " are not equal, but actor1.equals(actor2) returned true", actor1.equals(actor2));
        actor1.family = null;
        assertTrue("actors " + actor1 + " and " + actor2 + " are equal, but actor1.equals(actor2) returned false", actor1.equals(actor2));
        actor2.family = "Williams";
        assertFalse("actors " + actor1 + " and " + actor2 + " are not equal, but actor1.equals(actor2) returned true", actor1.equals(actor2));
        actor1.family = "Williams";
        assertTrue("actors " + actor1 + " and " + actor2 + " are equal, but actor1.equals(actor2) returned false", actor1.equals(actor2));
    }

    @Test
    public void testUniformA() {
        checkNotObjectHashCode();
        // chiSquared critical value (DOF=10-1, prob=0.999) ~= 27.88
        testUniformity(10, 45);
    }

    @Test
    public void testUniformB() {
        checkNotObjectHashCode();
        // chiSquared critical value (DOF=50-1, prob=0.999) ~= 85.35
        testUniformity(50, 135);
    }

    private void testUniformity(int buckets, double chiSqCriticalValue) {
        Random r = new Random(7);
        int[] count = new int[buckets];
        int samples = buckets * HASH_ITERATIONS;
        for (int i = 0; i < samples; i++) {
            Q5Actor actor = actors[r.nextInt(actors.length)];
            int h = Math.abs(actor.hashCode()) % buckets;
            count[h]++;
        }

        double chiSq = chiSquaredUniform(samples, count);
        assertTrue("Distribution of hash function doesn't appear to be uniform over " + buckets + " buckets (chi squared value of " + chiSq + ").\nExpected " + samples / buckets + " elements per bucket, but got " + Arrays.toString(count), chiSq < chiSqCriticalValue);
    }

    private void checkNotObjectHashCode() {
        Random r = new Random(9);
        int range = 39;
        Consumer<Function<Q5Actor, Integer>> checkHash = (Function<Q5Actor, Integer> hashFunction) -> {
            Set<Q5Actor>[] myBuckets = new Set[range];
            Set<Q5Actor>[] defaultBuckets = new Set[range];
            for (int i = 0; i < range; i++) {
                myBuckets[i] = new HashSet<>();
                defaultBuckets[i] = new HashSet<>();
            }
            for (int i = 0; i < 98 * HASH_ITERATIONS; i++) {
                Q5Actor actor = actors[r.nextInt(actors.length)];
                int m = Math.abs(actor.hashCode()) % range;
                myBuckets[m].add(actor);
                int n = Math.abs(hashFunction.apply(actor)) % range;
                defaultBuckets[n].add(actor);
            }
            for (Set<Q5Actor> myBucket : myBuckets) {
                for (Set<Q5Actor> defaultBucket : defaultBuckets) {
                    assertFalse("It looks like you're using Object.hashCode() or Objects.hash()!", myBucket.equals(defaultBucket));
                }
            }
        };

        checkHash.accept((Q5Actor actor) -> actor.passThroughHash());
        checkHash.accept((Q5Actor actor) -> Objects.hash(actor.given, actor.family, actor.dob));
        checkHash.accept((Q5Actor actor) -> Objects.hash(actor.given, actor.dob, actor.family));
        checkHash.accept((Q5Actor actor) -> Objects.hash(actor.family, actor.dob, actor.given));
        checkHash.accept((Q5Actor actor) -> Objects.hash(actor.family, actor.given, actor.dob));
        checkHash.accept((Q5Actor actor) -> Objects.hash(actor.dob, actor.given, actor.family));
        checkHash.accept((Q5Actor actor) -> Objects.hash(actor.dob, actor.family, actor.given));

    }

    private void testDifferent(Q5Actor actor1, Q5Actor actor2) {
        int hash1 = actor1.hashCode();
        int hash2 = actor2.hashCode();
        assertTrue("actors " + actor1 + " and " + actor2 + " returned same hashCode(): " + hash1 + ", " + hash2, hash1 != hash2);
    }

    @BeforeClass
    public static void generateActors() {
        Random r = new Random(11);
        for (int i = 0; i < actors.length; i++) {
            String[] base = actorlist[r.nextInt(actorlist.length)];
            actors[i] = new Q5Actor(base[0], base[1], String.format("%s%02d%02d", base[2], r.nextInt(12), r.nextInt(28)));
        }
    }

    private static double chiSquaredUniform(int samples, int[] counts) {
        double uniformProb = 1.0 / counts.length;
        double total = 0;
        for (int count : counts) {
            double mi = ((double) samples) * uniformProb;
            total += ((double) count - mi) * ((double) count - mi) / mi;
        }
        return total;
    }

    static String[][] actorlist = {
            {"Barkhad", "Abdi", "1985"},
            {"F. Murray", "Abraham", "1939"},
            {"Amy", "Adams", "1974"},
            {"Nick", "Adams", "1931"},
            {"Isabelle", "Adjani", "1955"},
            {"Casey", "Affleck", "1975"},
            {"Shohreh", "Aghdashloo", "1952"},
            {"Brian", "Aherne", "1902"},
            {"Danny", "Aiello", "1933"},
            {"Anouk", "Aimée", "1932"},
            {"Eddie", "Albert", "1906"},
            {"Jack", "Albertson", "1907"},
            {"Alan", "Alda", "1936"},
            {"Norma", "Aleandro", "1936"},
            {"Jane", "Alexander", "1939"},
            {"Mahershala", "Ali", "1974"},
            {"Joan", "Allen", "1956"},
            {"Woody", "Allen", "1935"},
            {"Sara", "Allgood", "1880"},
            {"Don", "Ameche", "1908"},
            {"Judith", "Anderson", "1897"},
            {"Julie", "Andrews", "1935"},
            {"Ann-Margret", "", "1941"},
            {"Yalitza", "Aparicio", "1993"},
            {"Anne", "Archer", "1947"},
            {"Eve", "Arden", "1908"},
            {"Alan", "Arkin", "1934"},
            {"George", "Arliss", "1868"},
            {"Patricia", "Arquette", "1968"},
            {"Jean", "Arthur", "1900"},
            {"Peggy", "Ashcroft", "1907"},
            {"Fred", "Astaire", "1899"},
            {"Mary", "Astor", "1906"},
            {"Mischa", "Auer", "1905"},
            {"Margaret", "Avery", "1944"},
            {"Dan", "Aykroyd", "1952"},
            {"Lew", "Ayres", "1908"},
            {"Lauren", "Bacall", "1924"},
            {"Hermione", "Baddeley", "1906"},
            {"Mary", "Badham", "1952"},
            {"Fay", "Bainter", "1893"},
            {"Carroll", "Baker", "1931"},
            {"Alec", "Baldwin", "1958"},
            {"Christian", "Bale", "1974"},
            {"Martin", "Balsam", "1919"},
            {"Anne", "Bancroft", "1931"},
            {"George", "Bancroft", "1882"},
            {"Antonio", "Banderas", "1960"},
            {"Ian", "Bannen", "1928"},
            {"Javier", "Bardem", "1969"},
            {"Marie-Christine", "Barrault", "1944"},
            {"Adriana", "Barraza", "1956"},
            {"Barbara", "Barrie", "1931"},
            {"Ethel", "Barrymore", "1879"},
            {"Lionel", "Barrymore", "1878"},
            {"Richard", "Barthelmess", "1895"},
            {"Mikhail", "Baryshnikov", "1948"},
            {"Kim", "Basinger", "1953"},
            {"Albert", "Bassermann", "1867"},
            {"Angela", "Bassett", "1958"},
            {"Alan", "Bates", "1934"},
            {"Kathy", "Bates", "1948"},
            {"Anne", "Baxter", "1923"},
            {"Warner", "Baxter", "1889"},
            {"Ned", "Beatty", "1937"},
            {"Warren", "Beatty", "1937"},
            {"Wallace", "Beery", "1885"},
            {"Ed", "Begley", "1901"},
            {"Bérénice", "Bejo", "1976"},
            {"Barbara Bel", "Geddes", "1922"},
            {"Ralph", "Bellamy", "1904"},
            {"William", "Bendix", "1906"},
            {"Roberto", "Benigni", "1952"},
            {"Annette", "Bening", "1958"},
            {"Tom", "Berenger", "1949"},
            {"Candice", "Bergen", "1946"},
            {"Ingrid", "Bergman", "1915"},
            {"Elisabeth", "Bergner", "1897"},
            {"Jeannie", "Berlin", "1949"},
            {"Halle", "Berry", "1966"},
            {"Demián", "Bichir", "1963"},
            {"Charles", "Bickford", "1891"},
            {"Theodore", "Bikel", "1924"},
            {"Juliette", "Binoche", "1964"},
            {"Karen", "Black", "1939"},
            {"Betsy", "Blair", "1923"},
            {"Linda", "Blair", "1959"},
            {"Ronee", "Blakley", "1945"},
            {"Cate", "Blanchett", "1969"},
            {"Brenda", "Blethyn", "1946"},
            {"Mary J.", "Blige", "1971"},
            {"Joan", "Blondell", "1906"},
            {"Ann", "Blyth", "1928"},
            {"Humphrey", "Bogart", "1899"},
            {"Beulah", "Bondi", "1889"},
            {"Helena Bonham", "Carter", "1966"},
            {"Shirley", "Booth", "1898"},
            {"Ernest", "Borgnine", "1917"},
            {"Charles", "Boyer", "1899"},
            {"Lorraine", "Bracco", "1954"},
            {"Alice", "Brady", "1892"},
            {"Kenneth", "Branagh", "1960"},
            {"Klaus Maria", "Brandauer", "1943"},
            {"Marlon Brando", "§", "1924"},
            {"Eileen", "Brennan", "1932"},
            {"Walter", "Brennan", "1894"},
            {"Abigail", "Breslin", "1996"},
            {"Jeff", "Bridges", "1949"},
            {"Jim", "Broadbent", "1949"},
            {"Adrien", "Brody", "1973"},
            {"Josh", "Brolin", "1968"},
            {"Albert", "Brooks", "1947"},
            {"Leslie", "Browne", "1957"},
            {"Yul", "Brynner", "1920"},
            {"Geneviève", "Bujold", "1942"},
            {"Sandra", "Bullock", "1964"},
            {"Victor", "Buono", "1938"},
            {"Billie", "Burke", "1884"},
            {"Catherine", "Burns", "1945"},
            {"George", "Burns", "1896"},
            {"Ellen", "Burstyn", "1932"},
            {"Richard", "Burton", "1925"},
            {"Gary", "Busey", "1944"},
            {"Red", "Buttons", "1919"},
            {"Spring", "Byington", "1886"},
            {"James", "Caan", "1940"},
            {"Adolph", "Caesar", "1933"},
            {"Nicolas", "Cage", "1964"},
            {"James", "Cagney", "1899"},
            {"Michael", "Caine", "1933"},
            {"Louis", "Calhern", "1895"},
            {"Dyan", "Cannon", "1937"},
            {"Steve", "Carell", "1962"},
            {"Harry", "Carey", "1878"},
            {"Lynn", "Carlin", "1938"},
            {"Art", "Carney", "1918"},
            {"Leslie", "Caron", "1931"},
            {"Diahann", "Carroll", "1935"},
            {"Nancy", "Carroll", "1903"},
            {"Peggy", "Cass", "1924"},
            {"John", "Cassavetes", "1929"},
            {"Seymour", "Cassel", "1935"},
            {"Richard S.", "Castellano", "1933"},
            {"Keisha", "Castle-Hughes", "1990"},
            {"George", "Chakiris", "1934"},
            {"Timothée", "Chalamet", "1995"},
            {"Jeff", "Chandler", "1918"},
            {"Carol", "Channing", "1921"},
            {"Stockard", "Channing", "1944"},
            {"Charlie", "Chaplin", "1889"},
            {"Jessica", "Chastain", "1977"},
            {"Ruth", "Chatterton", "1892"},
            {"Don", "Cheadle", "1964"},
            {"Michael", "Chekhov", "1891"},
            {"", "Cher", "1946"},
            {"Maurice", "Chevalier", "1888"},
            {"Julie", "Christie", "1940"},
            {"Thomas Haden", "Church", "1960"},
            {"Diane", "Cilento", "1933"},
            {"Candy", "Clark", "1947"},
            {"Patricia", "Clarkson", "1959"},
            {"Jill", "Clayburgh", "1944"},
            {"Montgomery", "Clift", "1920"},
            {"George", "Clooney", "1961"},
            {"Glenn", "Close", "1947"},
            {"Lee J.", "Cobb", "1911"},
            {"Charles", "Coburn", "1877"},
            {"James", "Coburn", "1928"},
            {"James", "Coco", "1930"},
            {"Claudette", "Colbert", "1903"},
            {"Toni", "Collette", "1972"},
            {"Patricia", "Collinge", "1892"},
            {"Pauline", "Collins", "1940"},
            {"Olivia", "Colman", "1974"},
            {"Ronald", "Colman", "1891"},
            {"Betty", "Compson", "1897"},
            {"Jennifer", "Connelly", "1970"},
            {"Sean", "Connery", "1930"},
            {"Tom", "Conti", "1941"},
            {"Bradley", "Cooper", "1975"},
            {"Chris", "Cooper", "1951"},
            {"Gary", "Cooper", "1901"},
            {"Gladys", "Cooper", "1888"},
            {"Jackie", "Cooper", "1922"},
            {"Ellen", "Corby", "1911"},
            {"Valentina", "Cortese", "1923"},
            {"Kevin", "Costner", "1955"},
            {"Marion", "Cotillard", "1975"},
            {"Tom", "Courtenay", "1937"},
            {"Jeanne", "Crain", "1925"},
            {"Bryan", "Cranston", "1956"},
            {"Broderick", "Crawford", "1911"},
            {"Joan", "Crawford", "1904"},
            {"Donald", "Crisp", "1882"},
            {"James", "Cromwell", "1940"},
            {"Hume", "Cronyn", "1911"},
            {"Bing", "Crosby", "1903"},
            {"Rupert", "Crosse", "1927"},
            {"Lindsay", "Crouse", "1948"},
            {"Russell", "Crowe", "1964"},
            {"Tom", "Cruise", "1962"},
            {"Penélope", "Cruz", "1974"},
            {"Benedict", "Cumberbatch", "1976"},
            {"Quinn", "Cummings", "1967"},
            {"Tony", "Curtis", "1925"},
            {"Joan", "Cusack", "1962"},
            {"Willem", "Dafoe", "1955"},
            {"Dan", "Dailey", "1915"},
            {"John", "Dall", "1920"},
            {"Matt", "Damon", "1970"},
            {"Dorothy", "Dandridge", "1922"},
            {"Bobby", "Darin", "1936"},
            {"Jane", "Darwell", "1879"},
            {"Jaye", "Davidson", "1968"},
            {"Bette", "Davis", "1908"},
            {"Geena", "Davis", "1956"},
            {"Judy", "Davis", "1955"},
            {"Viola", "Davis", "1965"},
            {"Bruce", "Davison", "1946"},
            {"Doris", "Day", "1922"},
            {"Daniel", "Day-Lewis", "1957"},
            {"Olivia de", "Havilland", "1916"},
            {"Robert De", "Niro", "1943"},
            {"Vittorio De", "Sica", "1901"},
            {"Marina de", "Tavira", "1974"},
            {"James", "Dean", "1931"},
            {"Ruby", "Dee", "1922"},
            {"Benicio del", "Toro", "1967"},
            {"William", "Demarest", "1892"},
            {"Judi", "Dench", "1934"},
            {"Catherine", "Deneuve", "1943"},
            {"Sandy", "Dennis", "1937"},
            {"Gérard", "Depardieu", "1948"},
            {"Johnny", "Depp", "1963"},
            {"Bruce", "Dern", "1936"},
            {"Laura", "Dern", "1967"},
            {"Brandon", "deWilde", "1942"},
            {"Leonardo", "DiCaprio", "1974"},
            {"Marlene", "Dietrich", "1901"},
            {"Matt", "Dillon", "1964"},
            {"Melinda", "Dillon", "1939"},
            {"Richard", "Dix", "1893"},
            {"Robert", "Donat", "1905"},
            {"Brian", "Donlevy", "1901"},
            {"Kirk", "Douglas", "1916"},
            {"Melvyn", "Douglas", "1901"},
            {"Michael", "Douglas", "1944"},
            {"Brad", "Dourif", "1950"},
            {"Robert Downey", "Jr.", "1965"},
            {"Louise", "Dresser", "1878"},
            {"Marie", "Dressler", "1868"},
            {"Richard", "Dreyfuss", "1947"},
            {"Adam", "Driver", "1983"},
            {"Minnie", "Driver", "1970"},
            {"Jean", "Dujardin", "1972"},
            {"Olympia", "Dukakis", "1931"},
            {"Patty", "Duke", "1946"},
            {"Faye", "Dunaway", "1941"},
            {"Michael Clarke", "Duncan", "1957"},
            {"James", "Dunn", "1901"},
            {"Michael", "Dunn", "1934"},
            {"Irene", "Dunne", "1898"},
            {"Mildred", "Dunnock", "1901"},
            {"Charles", "Durning", "1923"},
            {"Robert", "Duvall", "1931"},
            {"Jeanne", "Eagels", "1890"},
            {"Clint", "Eastwood", "1930"},
            {"Samantha", "Eggar", "1939"},
            {"Jesse", "Eisenberg", "1983"},
            {"Chiwetel", "Ejiofor", "1977"},
            {"Denholm", "Elliott", "1922"},
            {"Sam", "Elliott", "1944"},
            {"Hope", "Emerson", "1897"},
            {"Cynthia", "Erivo", "1987"},
            {"Stuart", "Erwin", "1903"},
            {"Edith", "Evans", "1888"},
            {"Peter", "Falk", "1927"},
            {"Vera", "Farmiga", "1973"},
            {"Richard", "Farnsworth", "1920"},
            {"Michael", "Fassbender", "1977"},
            {"José", "Ferrer", "1912"},
            {"Sally", "Field", "1946"},
            {"Ralph", "Fiennes", "1962"},
            {"Peter", "Finch", "1916"},
            {"Frank", "Finlay", "1926"},
            {"Albert", "Finney", "1936"},
            {"Colin", "Firth", "1960"},
            {"Peter", "Firth", "1953"},
            {"Laurence", "Fishburne", "1961"},
            {"Barry", "Fitzgerald", "1888"},
            {"Geraldine", "Fitzgerald", "1913"},
            {"Louise", "Fletcher", "1934"},
            {"Nina", "Foch", "1924"},
            {"Henry", "Fonda", "1905"},
            {"Jane", "Fonda", "1937"},
            {"Peter", "Fonda", "1940"},
            {"Joan", "Fontaine", "1917"},
            {"Lynn", "Fontanne", "1887"},
            {"Harrison", "Ford", "1942"},
            {"Frederic", "Forrest", "1936"},
            {"Robert", "Forster", "1941"},
            {"Jodie", "Foster", "1962"},
            {"Jamie", "Foxx", "1967"},
            {"Anthony", "Franciosa", "1928"},
            {"James", "Franco", "1978"},
            {"Morgan", "Freeman", "1937"},
            {"Leonard", "Frey", "1938"},
            {"Brenda", "Fricker", "1945"},
            {"Clark", "Gable", "1901"},
            {"Lady", "Gaga", "1986"},
            {"Greta", "Garbo", "1905"},
            {"Andy", "García", "1956"},
            {"Vincent", "Gardenia", "1920"},
            {"Ava", "Gardner", "1922"},
            {"Andrew", "Garfield", "1983"},
            {"John", "Garfield", "1913"},
            {"William", "Gargan", "1905"},
            {"Judy", "Garland", "1922"},
            {"James", "Garner", "1928"},
            {"Teri", "Garr", "1944"},
            {"Greer", "Garson", "1904"},
            {"Janet", "Gaynor", "1906"},
            {"Michael V.", "Gazzo", "1923"},
            {"Leo", "Genn", "1905"},
            {"Chief Dan", "George", "1899"},
            {"Gladys", "George", "1904"},
            {"Paul", "Giamatti", "1967"},
            {"Giancarlo", "Giannini", "1942"},
            {"John", "Gielgud", "1904"},
            {"Jack", "Gilford", "1907"},
            {"Lillian", "Gish", "1893"},
            {"Jackie", "Gleason", "1916"},
            {"James", "Gleason", "1882"},
            {"Paulette", "Goddard", "1910"},
            {"Whoopi", "Goldberg", "1955"},
            {"Thomas", "Gomez", "1905"},
            {"Cuba Gooding", "Jr.", "1968"},
            {"Dexter", "Gordon", "1923"},
            {"Ruth", "Gordon", "1896"},
            {"Ryan", "Gosling", "1980"},
            {"Louis Gossett", "Jr.", "1936"},
            {"Elliott", "Gould", "1938"},
            {"Gloria", "Grahame", "1923"},
            {"Cary", "Grant", "1904"},
            {"Lee", "Grant", "1925"},
            {"Richard E.", "Grant", "1957"},
            {"Bonita", "Granville", "1923"},
            {"Graham", "Greene", "1952"},
            {"Sydney", "Greenstreet", "1879"},
            {"Joel", "Grey", "1932"},
            {"Corinne", "Griffith", "1894"},
            {"Hugh", "Griffith", "1912"},
            {"Melanie", "Griffith", "1957"},
            {"Rachel", "Griffiths", "1968"},
            {"Alec", "Guinness", "1914"},
            {"Edmund", "Gwenn", "1877"},
            {"Jake", "Gyllenhaal", "1980"},
            {"Maggie", "Gyllenhaal", "1977"},
            {"Joan", "Hackett", "1934"},
            {"Gene", "Hackman", "1930"},
            {"Jean", "Hagen", "1923"},
            {"Jackie Earle", "Haley", "1961"},
            {"Grayson", "Hall", "1922"},
            {"Tom", "Hanks", "1956"},
            {"Marcia Gay", "Harden", "1959"},
            {"Ann", "Harding", "1902"},
            {"Tom", "Hardy", "1977"},
            {"Tess", "Harper", "1950"},
            {"Woody", "Harrelson", "1961"},
            {"Barbara", "Harris", "1935"},
            {"Ed", "Harris", "1950"},
            {"Julie", "Harris", "1925"},
            {"Naomie", "Harris", "1976"},
            {"Richard", "Harris", "1930"},
            {"Rosemary", "Harris", "1927"},
            {"Rex", "Harrison", "1908"},
            {"Elizabeth", "Hartman", "1943"},
            {"Laurence", "Harvey", "1928"},
            {"Anne", "Hathaway", "1982"},
            {"Ethan", "Hawke", "1970"},
            {"John", "Hawkes", "1959"},
            {"Sally", "Hawkins", "1976"},
            {"Goldie", "Hawn", "1945"},
            {"Nigel", "Hawthorne", "1929"},
            {"Sessue", "Hayakawa", "1889"},
            {"Salma", "Hayek", "1966"},
            {"Helen", "Hayes", "1900"},
            {"Susan", "Hayward", "1917"},
            {"Eileen", "Heckart", "1919"},
            {"Lucas", "Hedges", "1996"},
            {"Van", "Heflin", "1908"},
            {"Mariel", "Hemingway", "1961"},
            {"Justin", "Henry", "1971"},
            {"Taraji P.", "Henson", "1970"},
            {"Audrey", "Hepburn", "1929"},
            {"Katharine", "Hepburn", "1907"},
            {"Barbara", "Hershey", "1948"},
            {"Charlton", "Heston", "1923"},
            {"William", "Hickey", "1927"},
            {"Jonah", "Hill", "1983"},
            {"Wendy", "Hiller", "1912"},
            {"Judd", "Hirsch", "1935"},
            {"Dustin", "Hoffman", "1937"},
            {"Philip Seymour", "Hoffman", "1967"},
            {"Hal", "Holbrook", "1925"},
            {"William", "Holden", "1918"},
            {"Judy", "Holliday", "1921"},
            {"Stanley", "Holloway", "1890"},
            {"Celeste", "Holm", "1917"},
            {"Ian", "Holm", "1931"},
            {"Oskar", "Homolka", "1898"},
            {"Anthony", "Hopkins", "1937"},
            {"Miriam", "Hopkins", "1902"},
            {"Dennis", "Hopper", "1936"},
            {"Bob", "Hoskins", "1942"},
            {"Djimon", "Hounsou", "1964"},
            {"John", "Houseman", "1902"},
            {"Leslie", "Howard", "1893"},
            {"Terrence", "Howard", "1969"},
            {"Trevor", "Howard", "1913"},
            {"Jennifer", "Hudson", "1981"},
            {"Kate", "Hudson", "1979"},
            {"Rock", "Hudson", "1925"},
            {"Felicity", "Huffman", "1962"},
            {"Tom", "Hulce", "1953"},
            {"Josephine", "Hull", "1877"},
            {"Arthur", "Hunnicutt", "1910"},
            {"Helen", "Hunt", "1963"},
            {"Linda", "Hunt", "1945"},
            {"Holly", "Hunter", "1958"},
            {"Kim", "Hunter", "1922"},
            {"Isabelle", "Huppert", "1953"},
            {"John", "Hurt", "1940"},
            {"William", "Hurt", "1950"},
            {"Ruth", "Hussey", "1911"},
            {"Anjelica", "Huston", "1951"},
            {"John", "Huston", "1906"},
            {"Walter", "Huston", "1883"},
            {"Timothy", "Hutton", "1960"},
            {"Martha", "Hyer", "1924"},
            {"John", "Ireland", "1914"},
            {"Jeremy", "Irons", "1948"},
            {"Amy", "Irving", "1953"},
            {"Burl", "Ives", "1909"},
            {"Hugh", "Jackman", "1968"},
            {"Glenda", "Jackson", "1936"},
            {"Samuel L.", "Jackson", "1948"},
            {"Richard", "Jaeckel", "1926"},
            {"Sam", "Jaffe", "1891"},
            {"Dean", "Jagger", "1903"},
            {"Allison", "Janney", "1959"},
            {"Emil", "Jannings", "1884"},
            {"Marianne", "Jean-Baptiste", "1967"},
            {"Richard", "Jenkins", "1947"},
            {"Scarlett", "Johansson", "1984"},
            {"Glynis", "Johns", "1923"},
            {"Ben", "Johnson", "1918"},
            {"Celia", "Johnson", "1908"},
            {"Angelina", "Jolie", "1975"},
            {"Carolyn", "Jones", "1930"},
            {"Felicity", "Jones", "1983"},
            {"James Earl", "Jones", "1931"},
            {"Jennifer", "Jones", "1919"},
            {"Shirley", "Jones", "1934"},
            {"Tommy Lee", "Jones", "1946"},
            {"Katy", "Jurado", "1924"},
            {"Madeline", "Kahn", "1942"},
            {"Daniel", "Kaluuya", "1989"},
            {"Ida", "Kamińska", "1899"},
            {"Carol", "Kane", "1952"},
            {"Diane", "Keaton", "1946"},
            {"Michael", "Keaton", "1951"},
            {"Lila", "Kedrova", "1918"},
            {"Catherine", "Keener", "1959"},
            {"Harvey", "Keitel", "1939"},
            {"Cecil", "Kellaway", "1890"},
            {"Sally", "Kellerman", "1937"},
            {"Gene", "Kelly", "1912"},
            {"Grace", "Kelly", "1929"},
            {"Nancy", "Kelly", "1921"},
            {"Anna", "Kendrick", "1985"},
            {"Arthur", "Kennedy", "1914"},
            {"George", "Kennedy", "1925"},
            {"Deborah", "Kerr", "1921"},
            {"Nicole", "Kidman", "1967"},
            {"Rinko", "Kikuchi", "1981"},
            {"Regina", "King", "1971"},
            {"Ben", "Kingsley", "1943"},
            {"Greg", "Kinnear", "1963"},
            {"Sally", "Kirkland", "1941"},
            {"Kevin", "Kline", "1947"},
            {"Shirley", "Knight", "1936"},
            {"Keira", "Knightley", "1985"},
            {"Alexander", "Knox", "1907"},
            {"Susan", "Kohner", "1936"},
            {"Miliza", "Korjus", "1909"},
            {"Jack", "Kruschen", "1922"},
            {"Diane", "Ladd", "1935"},
            {"Jocelyne", "LaGarde", "1924"},
            {"Christine", "Lahti", "1950"},
            {"Burt", "Lancaster", "1913"},
            {"Elsa", "Lanchester", "1902"},
            {"Martin", "Landau", "1928"},
            {"Diane", "Lane", "1965"},
            {"Hope", "Lange", "1933"},
            {"Jessica", "Lange", "1949"},
            {"Frank", "Langella", "1938"},
            {"Angela", "Lansbury", "1925"},
            {"Brie", "Larson", "1989"},
            {"Queen", "Latifah", "1970"},
            {"Charles", "Laughton", "1899"},
            {"Piper", "Laurie", "1932"},
            {"Jude", "Law", "1972"},
            {"Jennifer", "Lawrence", "1990"},
            {"Eva Le", "Gallienne", "1899"},
            {"Cloris", "Leachman", "1926"},
            {"Heath", "Ledger", "1979"},
            {"Peggy", "Lee", "1920"},
            {"Andrea", "Leeds", "1914"},
            {"Janet", "Leigh", "1927"},
            {"Jennifer Jason", "Leigh", "1962"},
            {"Vivien", "Leigh", "1913"},
            {"Margaret", "Leighton", "1922"},
            {"Jack", "Lemmon", "1925"},
            {"Lotte", "Lenya", "1898"},
            {"Melissa", "Leo", "1960"},
            {"Michael", "Lerner", "1941"},
            {"Jared", "Leto", "1971"},
            {"Juliette", "Lewis", "1973"},
            {"Laura", "Linney", "1964"},
            {"John", "Lithgow", "1945"},
            {"Sondra", "Locke", "1944"},
            {"Gene", "Lockhart", "1891"},
            {"Robert", "Loggia", "1930"},
            {"Carole", "Lombard", "1908"},
            {"Sophia", "Loren", "1934"},
            {"Joan", "Lorring", "1926"},
            {"Bessie", "Love", "1898"},
            {"Paul", "Lukas", "1891"},
            {"Alfred", "Lunt", "1892"},
            {"Ali", "MacGraw", "1939"},
            {"Shirley", "MacLaine", "1934"},
            {"Aline", "MacMahon", "1899"},
            {"William H.", "Macy", "1950"},
            {"Amy", "Madigan", "1950"},
            {"Virginia", "Madsen", "1961"},
            {"Anna", "Magnani", "1908"},
            {"Marjorie", "Main", "1890"},
            {"", "Mako", "1933"},
            {"Karl", "Malden", "1912"},
            {"Rami", "Malek", "1981"},
            {"John", "Malkovich", "1953"},
            {"Dorothy", "Malone", "1924"},
            {"Joe", "Mantell", "1915"},
            {"Lesley", "Manville", "1956"},
            {"Rooney", "Mara", "1985"},
            {"Fredric", "March", "1897"},
            {"Colette", "Marchand", "1925"},
            {"John", "Marley", "1907"},
            {"Lee", "Marvin", "1924"},
            {"James", "Mason", "1909"},
            {"Marsha", "Mason", "1942"},
            {"Daniel", "Massey", "1933"},
            {"Raymond", "Massey", "1896"},
            {"Mary E.", "Mastrantonio", "1958"},
            {"Marcello", "Mastroianni", "1924"},
            {"Marlee", "Matlin", "1965"},
            {"Walter", "Matthau", "1920"},
            {"Rachel", "McAdams", "1978"},
            {"Mercedes", "McCambridge", "1916"},
            {"Kevin", "McCarthy", "1914"},
            {"Melissa", "McCarthy", "1970"},
            {"Matthew", "McConaughey", "1969"},
            {"Patty", "McCormack", "1945"},
            {"Hattie", "McDaniel", "1895"},
            {"Mary", "McDonnell", "1952"},
            {"Frances", "McDormand", "1957"},
            {"Elizabeth", "McGovern", "1961"},
            {"Dorothy", "McGuire", "1916"},
            {"Ian", "McKellen", "1939"},
            {"Victor", "McLaglen", "1886"},
            {"Maggie", "McNamara", "1928"},
            {"Steve", "McQueen", "1930"},
            {"Janet", "McTeer", "1961"},
            {"Kay", "Medford", "1919"},
            {"Adolphe", "Menjou", "1890"},
            {"Vivien", "Merchant", "1929"},
            {"Melina", "Mercouri", "1920"},
            {"Burgess", "Meredith", "1907"},
            {"Una", "Merkel", "1903"},
            {"Laurie", "Metcalf", "1955"},
            {"Bette", "Midler", "1945"},
            {"Sarah", "Miles", "1941"},
            {"Sylvia", "Miles", "1924"},
            {"Penelope", "Milford", "1948"},
            {"Ray", "Milland", "1907"},
            {"Jason", "Miller", "1939"},
            {"John", "Mills", "1908"},
            {"Sal", "Mineo", "1939"},
            {"Liza", "Minnelli", "1946"},
            {"Helen", "Mirren", "1945"},
            {"Thomas", "Mitchell", "1892"},
            {"Robert", "Mitchum", "1917"},
            {"Mo'Nique", "", "1967"},
            {"Fernanda", "Montenegro", "1929"},
            {"Robert", "Montgomery", "1904"},
            {"Ron", "Moody", "1924"},
            {"Dudley", "Moore", "1935"},
            {"Grace", "Moore", "1898"},
            {"Juanita", "Moore", "1914"},
            {"Julianne", "Moore", "1960"},
            {"Mary Tyler", "Moore", "1936"},
            {"Terry", "Moore", "1929"},
            {"Agnes", "Moorehead", "1900"},
            {"Rita", "Moreno", "1931"},
            {"Frank", "Morgan", "1890"},
            {"Cathy", "Moriarty", "1960"},
            {"Pat", "Morita", "1932"},
            {"Robert", "Morley", "1908"},
            {"Chester", "Morris", "1901"},
            {"Viggo", "Mortensen", "1958"},
            {"Samantha", "Morton", "1977"},
            {"Armin", "Mueller-Stahl", "1930"},
            {"Carey", "Mulligan", "1985"},
            {"Paul", "Muni", "1895"},
            {"Eddie", "Murphy", "1961"},
            {"Bill", "Murray", "1950"},
            {"Don", "Murray", "1929"},
            {"J. Carrol", "Naish", "1896"},
            {"Mildred", "Natwick", "1905"},
            {"Patricia", "Neal", "1926"},
            {"Liam", "Neeson", "1952"},
            {"Ruth", "Negga", "1982"},
            {"Kate", "Nelligan", "1950"},
            {"Paul", "Newman", "1925"},
            {"Haing S.", "Ngor", "1940"},
            {"Jack", "Nicholson", "1937"},
            {"David", "Niven", "1910"},
            {"Nick", "Nolte", "1941"},
            {"Edward", "Norton", "1969"},
            {"Lupita", "Nyong'o", "1983"},
            {"Edmond", "O'Brien", "1915"},
            {"Arthur", "O'Connell", "1908"},
            {"Dan", "O'Herlihy", "1919"},
            {"Michael", "O'Keefe", "1955"},
            {"Ryan", "O'Neal", "1941"},
            {"Tatum", "O'Neal", "1963"},
            {"Barbara", "O'Neil", "1910"},
            {"Peter", "O'Toole", "1932"},
            {"Jack", "Oakie", "1903"},
            {"Merle", "Oberon", "1911"},
            {"Sophie", "Okonedo", "1968"},
            {"Gary", "Oldman", "1958"},
            {"Lena", "Olin", "1955"},
            {"Edna May", "Oliver", "1883"},
            {"Laurence", "Olivier", "1907"},
            {"Edward James", "Olmos", "1947"},
            {"Nancy", "Olson", "1928"},
            {"Haley Joel", "Osment", "1988"},
            {"Maria", "Ouspenskaya", "1876"},
            {"Clive", "Owen", "1964"},
            {"Al", "Pacino", "1940"},
            {"Elliot", "Page", "1987"},
            {"Geraldine", "Page", "1924"},
            {"Jack", "Palance", "1919"},
            {"Chazz", "Palminteri", "1952"},
            {"Gwyneth", "Paltrow", "1972"},
            {"Anna", "Paquin", "1982"},
            {"Eleanor", "Parker", "1922"},
            {"Larry", "Parks", "1914"},
            {"Estelle", "Parsons", "1927"},
            {"Dev", "Patel", "1990"},
            {"Marisa", "Pavan", "1932"},
            {"Katina", "Paxinou", "1900"},
            {"David", "Paymer", "1954"},
            {"Gregory", "Peck", "1916"},
            {"Sean", "Penn", "1960"},
            {"Rosie", "Perez", "1964"},
            {"Anthony", "Perkins", "1932"},
            {"Valerie", "Perrine", "1943"},
            {"Joe", "Pesci", "1943"},
            {"Susan", "Peters", "1921"},
            {"Michelle", "Pfeiffer", "1958"},
            {"Joaquin", "Phoenix", "1974"},
            {"River", "Phoenix", "1970"},
            {"Mary", "Pickford", "1892"},
            {"Walter", "Pidgeon", "1897"},
            {"Rosamund", "Pike", "1979"},
            {"Brad", "Pitt", "1963"},
            {"Joan", "Plowright", "1929"},
            {"Christopher", "Plummer", "1929"},
            {"Sidney", "Poitier", "1927"},
            {"Michael J.", "Pollard", "1939"},
            {"Natalie", "Portman", "1981"},
            {"Pete", "Postlethwaite", "1946"},
            {"William", "Powell", "1892"},
            {"Robert", "Preston", "1918"},
            {"Jonathan", "Pryce", "1947"},
            {"Florence", "Pugh", "1996"},
            {"Randy", "Quaid", "1950"},
            {"Anthony", "Quayle", "1913"},
            {"Kathleen", "Quinlan", "1954"},
            {"Anthony", "Quinn", "1915"},
            {"Luise", "Rainer", "1910"},
            {"Claude", "Rains", "1889"},
            {"Marjorie", "Rambeau", "1889"},
            {"Charlotte", "Rampling", "1946"},
            {"Anne", "Ramsey", "1929"},
            {"Basil", "Rathbone", "1892"},
            {"Stephen", "Rea", "1946"},
            {"Robert", "Redford", "1936"},
            {"Lynn", "Redgrave", "1943"},
            {"Michael", "Redgrave", "1908"},
            {"Vanessa", "Redgrave", "1937"},
            {"Joyce", "Redman", "1915"},
            {"Eddie", "Redmayne", "1982"},
            {"Donna", "Reed", "1921"},
            {"John C.", "Reilly", "1965"},
            {"Lee", "Remick", "1935"},
            {"Jeremy", "Renner", "1971"},
            {"Anne", "Revere", "1903"},
            {"Burt", "Reynolds", "1936"},
            {"Debbie", "Reynolds", "1932"},
            {"Beah", "Richards", "1920"},
            {"Miranda", "Richardson", "1958"},
            {"Ralph", "Richardson", "1902"},
            {"Thelma", "Ritter", "1902"},
            {"Emmanuelle", "Riva", "1927"},
            {"Jason", "Robards", "1922"},
            {"Margot", "Robbie", "1990"},
            {"Tim", "Robbins", "1958"},
            {"Eric", "Roberts", "1956"},
            {"Julia", "Roberts", "1967"},
            {"Rachel", "Roberts", "1927"},
            {"Cliff", "Robertson", "1923"},
            {"Flora", "Robson", "1902"},
            {"May", "Robson", "1858"},
            {"Sam", "Rockwell", "1968"},
            {"Ginger", "Rogers", "1911"},
            {"Howard", "Rollins", "1950"},
            {"Saoirse", "Ronan", "1994"},
            {"Mickey", "Rooney", "1920"},
            {"Diana", "Ross", "1944"},
            {"Katharine", "Ross", "1940"},
            {"Tim", "Roth", "1961"},
            {"Mickey", "Rourke", "1952"},
            {"Gena", "Rowlands", "1930"},
            {"Mercedes", "Ruehl", "1948"},
            {"Mark", "Ruffalo", "1967"},
            {"Geoffrey", "Rush", "1951"},
            {"Harold", "Russell", "1914"},
            {"Rosalind", "Russell", "1907"},
            {"Margaret", "Rutherford", "1892"},
            {"Amy", "Ryan", "1969"},
            {"Robert", "Ryan", "1909"},
            {"Winona", "Ryder", "1971"},
            {"Mark", "Rylance", "1960"},
            {"Eva Marie", "Saint", "1924"},
            {"George", "Sanders", "1906"},
            {"Catalina Sandino", "Moreno", "1981"},
            {"Chris", "Sarandon", "1942"},
            {"Susan", "Sarandon", "1946"},
            {"Telly", "Savalas", "1922"},
            {"Diana", "Scarwid", "1955"},
            {"Roy", "Scheider", "1932"},
            {"Maximilian", "Schell", "1930"},
            {"Joseph", "Schildkraut", "1896"},
            {"Paul", "Scofield", "1922"},
            {"George C. Scott", "§", "1927"},
            {"Martha", "Scott", "1912"},
            {"Kristin Scott", "Thomas", "1960"},
            {"George", "Segal", "1934"},
            {"Peter", "Sellers", "1925"},
            {"Chloë", "Sevigny", "1974"},
            {"Michael", "Shannon", "1974"},
            {"Omar", "Sharif", "1932"},
            {"Robert", "Shaw", "1927"},
            {"Norma", "Shearer", "1902"},
            {"Sam", "Shepard", "1943"},
            {"Talia", "Shire", "1946"},
            {"Anne", "Shirley", "1918"},
            {"Elisabeth", "Shue", "1963"},
            {"Gabourey", "Sidibe", "1983"},
            {"Sylvia", "Sidney", "1910"},
            {"Simone", "Signoret", "1921"},
            {"J. K.", "Simmons", "1955"},
            {"Jean", "Simmons", "1929"},
            {"Frank", "Sinatra", "1915"},
            {"Gary", "Sinise", "1955"},
            {"Lilia", "Skala", "1896"},
            {"Maggie", "Smith", "1934"},
            {"Will", "Smith", "1968"},
            {"Carrie", "Snodgress", "1945"},
            {"Gale", "Sondergaard", "1899"},
            {"Mira", "Sorvino", "1967"},
            {"Ann", "Sothern", "1909"},
            {"Sissy", "Spacek", "1949"},
            {"Kevin", "Spacey", "1959"},
            {"Octavia", "Spencer", "1972"},
            {"June", "Squibb", "1929"},
            {"Robert", "Stack", "1919"},
            {"Sylvester", "Stallone", "1946"},
            {"Terence", "Stamp", "1938"},
            {"Kim", "Stanley", "1925"},
            {"Barbara", "Stanwyck", "1907"},
            {"Maureen", "Stapleton", "1925"},
            {"Imelda", "Staunton", "1956"},
            {"Mary", "Steenburgen", "1953"},
            {"Rod", "Steiger", "1925"},
            {"Hailee", "Steinfeld", "1996"},
            {"James", "Stephenson", "1889"},
            {"Jan", "Sterling", "1921"},
            {"James", "Stewart", "1908"},
            {"Dean", "Stockwell", "1936"},
            {"Emma", "Stone", "1988"},
            {"Lewis", "Stone", "1879"},
            {"Sharon", "Stone", "1958"},
            {"Beatrice", "Straight", "1914"},
            {"Lee", "Strasberg", "1901"},
            {"David", "Strathairn", "1949"},
            {"Robert", "Strauss", "1913"},
            {"Meryl", "Streep", "1949"},
            {"Barbra", "Streisand", "1942"},
            {"Erich von", "Stroheim", "1885"},
            {"Gloria", "Stuart", "1910"},
            {"Margaret", "Sullavan", "1909"},
            {"Janet", "Suzman", "1939"},
            {"Hilary", "Swank", "1974"},
            {"Gloria", "Swanson", "1899"},
            {"Tilda", "Swinton", "1960"},
            {"Russ", "Tamblyn", "1934"},
            {"Akim", "Tamiroff", "1899"},
            {"Jessica", "Tandy", "1909"},
            {"Elizabeth", "Taylor", "1932"},
            {"Charlize", "Theron", "1975"},
            {"Emma", "Thompson", "1959"},
            {"Billy Bob", "Thornton", "1955"},
            {"Uma", "Thurman", "1970"},
            {"Lawrence", "Tibbett", "1896"},
            {"Gene", "Tierney", "1920"},
            {"Jennifer", "Tilly", "1958"},
            {"Meg", "Tilly", "1960"},
            {"Richard", "Todd", "1919"},
            {"Marisa", "Tomei", "1964"},
            {"Lily", "Tomlin", "1939"},
            {"Franchot", "Tone", "1905"},
            {"Topol", "", "1935"},
            {"Rip", "Torn", "1931"},
            {"Lee", "Tracy", "1898"},
            {"Spencer", "Tracy", "1900"},
            {"Henry", "Travers", "1874"},
            {"John", "Travolta", "1954"},
            {"Claire", "Trevor", "1910"},
            {"Massimo", "Troisi", "1953"},
            {"Stanley", "Tucci", "1960"},
            {"Tom", "Tully", "1908"},
            {"Kathleen", "Turner", "1954"},
            {"Lana", "Turner", "1921"},
            {"Susan", "Tyrrell", "1945"},
            {"Cicely", "Tyson", "1924"},
            {"Liv", "Ullmann", "1938"},
            {"Miyoshi", "Umeki", "1929"},
            {"Mary", "Ure", "1933"},
            {"Peter", "Ustinov", "1921"},
            {"Brenda", "Vaccaro", "1939"},
            {"Jo Van", "Fleet", "1915"},
            {"Diane", "Varsi", "1938"},
            {"Robert", "Vaughn", "1932"},
            {"Alicia", "Vikander", "1988"},
            {"Jon", "Voight", "1938"},
            {"Max von", "Sydow", "1929"},
            {"Mark", "Wahlberg", "1971"},
            {"Christopher", "Walken", "1943"},
            {"Quvenzhané", "Wallis", "2003"},
            {"Julie", "Walters", "1950"},
            {"Christoph", "Waltz", "1956"},
            {"Jack", "Warden", "1920"},
            {"H. B.", "Warner", "1875"},
            {"Lesley Ann", "Warren", "1946"},
            {"Denzel", "Washington", "1954"},
            {"Ken", "Watanabe", "1959"},
            {"Ethel", "Waters", "1896"},
            {"Sam", "Waterston", "1940"},
            {"Emily", "Watson", "1967"},
            {"Lucile", "Watson", "1879"},
            {"Naomi", "Watts", "1968"},
            {"John", "Wayne", "1907"},
            {"Jacki", "Weaver", "1947"},
            {"Sigourney", "Weaver", "1949"},
            {"Clifton", "Webb", "1889"},
            {"Rachel", "Weisz", "1970"},
            {"Tuesday", "Weld", "1943"},
            {"Orson", "Welles", "1915"},
            {"Oskar", "Werner", "1922"},
            {"Forest", "Whitaker", "1961"},
            {"Stuart", "Whitman", "1928"},
            {"James", "Whitmore", "1921"},
            {"May", "Whitty", "1865"},
            {"Richard", "Widmark", "1914"},
            {"Dianne", "Wiest", "1948"},
            {"Jack", "Wild", "1952"},
            {"Cornel", "Wilde", "1912"},
            {"Gene", "Wilder", "1933"},
            {"Tom", "Wilkinson", "1948"},
            {"Cara", "Williams", "1925"},
            {"Michelle", "Williams", "1980"},
            {"Robin", "Williams", "1951"},
            {"Chill", "Wills", "1902"},
            {"Paul", "Winfield", "1939"},
            {"Oprah", "Winfrey", "1954"},
            {"Debra", "Winger", "1955"},
            {"Mare", "Winningham", "1959"},
            {"Kate", "Winslet", "1975"},
            {"Shelley", "Winters", "1920"},
            {"Reese", "Witherspoon", "1976"},
            {"Natalie", "Wood", "1938"},
            {"Peggy", "Wood", "1892"},
            {"Alfre", "Woodard", "1952"},
            {"James", "Woods", "1947"},
            {"Joanne", "Woodward", "1930"},
            {"Monty", "Woolley", "1888"},
            {"Teresa", "Wright", "1918"},
            {"Margaret", "Wycherly", "1881"},
            {"Jane", "Wyman", "1917"},
            {"Ed", "Wynn", "1886"},
            {"Diana", "Wynyard", "1906"},
            {"Susannah", "York", "1939"},
            {"Burt", "Young", "1940"},
            {"Gig", "Young", "1913"},
            {"Loretta", "Young", "1913"},
            {"Roland", "Young", "1887"},
            {"Renée", "Zellweger", "1969"},
            {"Catherine", "Zeta-Jones", "1969"},
    };
}
